[greeter]
background=/usr/share/backgrounds/doshy.png
theme-name=Arc-Dark
icon-theme-name=Papirus-Dark
font-name=DejaVu Sans 10
indicators=~host;~spacer;~clock;~spacer;~session;~a11y;~power
clock-format=%H:%M
position=50%,center 50%,center
# Show the list of users to pick from (like the Windows login screen)
hide-user-image=false
default-user-image=#avatar-default
panel-position=bottom
